Algoritmo "12 circulo"
// Disciplina   : [lógica de Programação e java script]
// Professor   : Jailson
// Descrição   : ler as dimensões do circulo
// Autor(a)    : Núbia
// Data atual  : 02/09/2022
Var
// Seção de Declarações das variáveis 
 raio:real
 area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("digite o valor do raio")
leia(raio)
area<-pi*raio^2
escreval("a area e:",area)

Fimalgoritmo